// Generated by CoffeeScript 1.7.1
var Negotiator;

Negotiator = require('negotiator');

exports.register = function(plugin, options, next) {
  if (options.exclude == null) {
    options.exclude = [];
  }
  plugin.route({
    method: 'GET',
    path: '/public/{path*}',
    handler: {
      directory: {
        path: "./public",
        listing: false,
        index: true
      }
    }
  });
  plugin.ext('onRequest', function(request, next) {
    var availableMediaTypes, negotiator;
    negotiator = new Negotiator(request.raw.req);
    availableMediaTypes = ['application/json', 'text/html'];
    if (options.exclude.some(function(path) {
      return new RegExp(path).test(request.path);
    })) {
      next();
    } else if (negotiator.preferredMediaType(availableMediaTypes) === "application/json") {
      next();
    } else if (negotiator.preferredMediaType(availableMediaTypes) === "text/html") {
      request.setUrl('/public/');
      next();
    } else {
      request.setUrl("/public" + request.path);
      next();
    }
  });
  return next();
};

exports.register.attributes = {
  name: 'hapi-single-page-app',
  version: '0.0.1'
};
